### PR TITLE
Add Procedure for reporting Core members, or other odin leadership

### PR DESCRIPTION
**Pull request by codyloyd**
This is an initial draft of some procedures that should be followed in the case that someone feels they need to report a Core member for misbehavior or whatever kind of infraction.

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]

**Review by I3uckwheat — CHANGES_REQUESTED** [review]
During our conversations in the mid-monthly meeting, it seems that there could be a bit of confusion around how this would work. The suggestions that came out of it were:

Adjust this to be a "staff guideline" to describe the process of how this would be escalated
  -  Some users may not have enough rapport with Core members to know who to reach out to, instead they could reach out to a maintainer or moderator and the maintainer or moderator would be responsible for escalating it to two trusted Core members in DMs. It would be the reportee's responsibility to handle that escalation.  We should also make it clear that this escalation can happen from any level (A core member can report a Core member in this way)
  
Add wording about how if a report isn't handled in a timely manner, (24 hours) it's OK to ask for a follow-up or report it to another member as things are often time sensitive. 

We will also add this process to the rules, a user without rapport should only have to reach out to *any* staff member privately.

**Review by rlmoser99 — COMMENTED** [review]
Should these guidelines go in the staff-guidelines, since they do pertain to all staff?
https://github.com/TheOdinProject/top-meta/pull/179

**Comment by codyloyd** [comment]
> Should these guidelines go in the staff-guidelines, since they do pertain to all staff?
> 
> Here is the open PR that divides staff and core guidelines: #179

yeah it should... but that document doesn't exist yet.  I'm not sure what the other PR is waiting on.

**Review by kashura — CHANGES_REQUESTED** [review]
I'd change lower case "core" to "Core".

**Pull request closed without merging**
